export const ActionTypes = {
  LOGIN: 'LOGIN',
  UPDATE_USERNAME: 'UPDATE_USERNAME',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  UPDATE_USERNAME_ERROR: 'UPDATE_USERNAME_ERROR',
  UPDATE_PASSWORD_ERROR: 'UPDATE_PASSWORD_ERROR',
  NAVIGATE: 'NAVIGATE',
  DEBUG: 'DEBUG',
  CLEAR_LOGIN_INPUTS: 'CLEAR_LOGIN_INPUTS'
}